title: Jarry Rizvi Resume
description:  A beautiful template for your CV.
url: https://jekyll-cv.stavrospanakakis.com
baseurl: '/JRResume'
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
